Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft.AspNetCore: Information

Seq:
  ServerUrl: http://localhost:5341

ReverseProxy:
  Clusters:
    users:
      Destinations:
        users-api:
          Address: http://localhost:5100/
    finance:
      Destinations:
        finance-api:
          Address: http://localhost:5200/
