Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.AspNetCore: Warning
  WriteTo:
    - Name: Console

Seq:
  ServerUrl: http://seq:5341

AllowedHosts: "*"

ReverseProxy:
  Routes:
    users:
      ClusterId: users
      Match:
        Path: "/users/{**catch-all}"
      Transforms:
        - PathRemovePrefix: "/users"
    finance:
      ClusterId: finance
      Match:
        Path: "/finance/{**catch-all}"
  Clusters:
    users:
      Destinations:
        users-api:
          Address: http://users-api:8080/
    finance:
      Destinations:
        finance-api:
          Address: http://finance-api:8080/
