Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
      Microsoft.EntityFrameworkCore: Warning
  WriteTo:
    - Name: Console

Seq:
  ServerUrl: http://seq:5341

Cbr:
  BaseUrl: http://www.cbr.ru

CurrencyWorker:
  SyncIntervalMinutes: 60
