Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.EntityFrameworkCore: Warning
  WriteTo:
    - Name: Console

Seq:
  ServerUrl: http://seq:5341
