Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.AspNetCore: Warning
      Microsoft.EntityFrameworkCore: Warning
  WriteTo:
    - Name: Console

Seq:
  ServerUrl: http://seq:5341

AllowedHosts: "*"

Jwt:
  Issuer: TrueCode
  Audience: TrueCodeClients
  AccessTokenMinutes: 15
  RefreshTokenDays: 7
